### ISSUE TITLE
Widget does not save contents when in code view

### ISSUE THREAD

**Issue by jbowen-hileman** [Kentico/ems-mvc-components#36]
Switch the widget to code view to edit html directly.
1. There's no way to switch out of code view.
2. The contents entered in code view do not save.

**Comment by tetz2442** [comment]
Can confirm this issue. Just ran into it

**Comment by OndraM-Kentico** [comment]
This is a known issue. It's caused by [bug](https://github.com/froala/wysiwyg-editor/issues/3639) in Froala editor and we're waiting for the fix.

**Comment by Atzie** [comment]
To clarify, it is actually possible to switch out of the code view and save your changes. In the code view when you put your mouse in the top right corner, a grey button will appear as seen here:
![image](https://user-images.githubusercontent.com/5427497/68914376-76fbad80-07b2-11ea-922f-a1de4789c91a.png) 
The bug is that the button icon is not being displayed. Clicking the grey square will bring you back to the content view. Any changes can then be saved.

**Comment by jbowen-hileman** [comment]
The main issue is that the contents entered in code view do not save when clicking the Save button. You have to switch out of code view first.
