### ISSUE TITLE
Installation as a NuGet package

### ISSUE THREAD

**Issue by tomhicklingnc** [Kentico/ems-mvc-components#68]
Can you please make this installable as a NuGet package? It's not really acceptable to expect us to clone the project, build it locally, then copy the DLLs and markup from this repository to our own. We need to be able to maintain actual versions of this package such that we can more easily upgrade it should a new version be released.

**Comment by liamgold** [comment]
I agree, it would be useful to have these installable as NuGet packages.

**Comment by OliverWatersNC** [comment]
Bump on the above.

**Comment by rshackleton** [comment]
The complexity of the installation instructions is ridiculous, the whole purpose of having components being open source is to allow easy usage of them. All of the described steps should be handled as part of a NuGet installation process as @tomhicklingnc has described.

Considering a decent quality WYSIWYG is something that should have shipped with the base vanilla Kentico 12 product it's a joke that the installation steps are as arduous as they are.

**Comment by rshackleton** [comment]
Also to clarify, this is in reference to the `Kentico.InlineEditor.RichText` package.

**Comment by davidkomarek** [comment]
Thanks for comments! We have the NuGet distribution already in the backlog and currently fine-tuning the richtext editor for its first release. You can expect the package around Xmas time (hard deadline is the 2nd K2020 beta at the beginning of January).

**Comment by tomhicklingnc** [comment]
Thanks for confirming David. You mind if we leave this ticket open in the meantime so I can be notified when this has been delivered?

**Comment by davidkomarek** [comment]
Sure thing, the dev team will update the status of this issue as part of the NuGet publishing task implementation.

**Comment by rpribyl** [comment]
Hello everyone, I'm happy to announce a fresh release of the Rich text editor via a [NuGet package](https://www.nuget.org/packages/Kentico.EMS12.MvcComponents.Widget.RichText).

You may ask why there is the "EMS12" part in the package name. It is because we are planning to include the Rich text editor in the default Kentico installation in the next Kentico version and this package won't be needed anymore.

Also, we'd like to let you know that there are some features coming soon into theis NuGet package like "linking media files" and "linking assets from Kentico into an image".
