### ISSUE TITLE
Nuget package adds file reference to project, but not the file referenced

### ISSUE THREAD

**Issue by CompDr** [Kentico/ems-mvc-components#80]
Nuget package adds a reference to Kentico.Widget.RichText.resx to the project, but not the file rex file. This causes the build to fail in Azure DevOps.

What went wrong?

### Repro steps

1. Install nuget package
2.  At this point it will build locally
3. COmmit changes to repo
4. Build project in Azure Devops

### Expected behavior

Include the missing file in the nuget package or remove the file reference from the project.

**Comment by rpribyl** [comment]
Hello,
The problem is that Visual Studio adds these resource files as "Embedded Resource". They are then compiled into an assembly and therefore are missing later. A quick workaround could be to change the build action of these resx files to "Content".

We'll remove the reference from the project file.
